// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/thn-lee/01-task-management-api/pkg/models/api"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: task
func (_m *TaskRepository) CreateTask(task models.Task) (models.Task, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Task) (models.Task, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(models.Task) models.Task); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Get(0).(models.Task)
	}

	if rf, ok := ret.Get(1).(func(models.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: taskID
func (_m *TaskRepository) DeleteTask(taskID uint) error {
	ret := _m.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditTask provides a mock function with given fields: taskID, requestTask
func (_m *TaskRepository) EditTask(taskID uint, requestTask models.Task) (models.Task, error) {
	ret := _m.Called(taskID, requestTask)

	if len(ret) == 0 {
		panic("no return value specified for EditTask")
	}

	var r0 models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, models.Task) (models.Task, error)); ok {
		return rf(taskID, requestTask)
	}
	if rf, ok := ret.Get(0).(func(uint, models.Task) models.Task); ok {
		r0 = rf(taskID, requestTask)
	} else {
		r0 = ret.Get(0).(models.Task)
	}

	if rf, ok := ret.Get(1).(func(uint, models.Task) error); ok {
		r1 = rf(taskID, requestTask)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditTaskStatus provides a mock function with given fields: taskID, status
func (_m *TaskRepository) EditTaskStatus(taskID uint, status string) (models.Task, error) {
	ret := _m.Called(taskID, status)

	if len(ret) == 0 {
		panic("no return value specified for EditTaskStatus")
	}

	var r0 models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string) (models.Task, error)); ok {
		return rf(taskID, status)
	}
	if rf, ok := ret.Get(0).(func(uint, string) models.Task); ok {
		r0 = rf(taskID, status)
	} else {
		r0 = ret.Get(0).(models.Task)
	}

	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(taskID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTask provides a mock function with given fields: taskID
func (_m *TaskRepository) GetTask(taskID uint) (models.Task, error) {
	ret := _m.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (models.Task, error)); ok {
		return rf(taskID)
	}
	if rf, ok := ret.Get(0).(func(uint) models.Task); ok {
		r0 = rf(taskID)
	} else {
		r0 = ret.Get(0).(models.Task)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTasks provides a mock function with given fields: criteria
func (_m *TaskRepository) ListTasks(criteria models.Task) (map[int]models.Task, error) {
	ret := _m.Called(criteria)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 map[int]models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Task) (map[int]models.Task, error)); ok {
		return rf(criteria)
	}
	if rf, ok := ret.Get(0).(func(models.Task) map[int]models.Task); ok {
		r0 = rf(criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(models.Task) error); ok {
		r1 = rf(criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
